### ISSUE TITLE
morty isn't available at your branches

### ISSUE THREAD

**Issue by ghost** [mont3z/meta-pine64#2]
![17](https://cloud.githubusercontent.com/assets/23099534/22619137/68f83df4-eb20-11e6-9e8a-ddff7468268c.png)

![18](https://cloud.githubusercontent.com/assets/23099534/22619161/f393e77e-eb20-11e6-9b26-39b16917e4fa.png)

**Comment by r1mikey** [comment]
master targets morty at present, so you can just use master for your build.
