### ISSUE TITLE
bitbake u-boot-pine64 fails

### ISSUE THREAD

**Issue by JanP** [mont3z/meta-pine64#3]
Using latest master, the build of u-boot-pine64 fails with a missing script, script_pine64.
Any ideas why this is. The script is nowhere to be found in the sysroot or buildroot.

**Comment by r3dlight** [comment]
+1, same here (poky+master branch)

**Comment by mont3z** [comment]
This script is created by recipe sunxitools-native_1.0.bb, which compiles from repository mont3z/sunxi-pack-tools. Unfortunately I'm busy on other projects at the moment. I'd appreciate if anyone could help fix this. Thx.
