### ISSUE TITLE
Active development?

### ISSUE THREAD

**Issue by ndechesne** [mont3z/meta-pine64#6]
hey,

is this project still active? There doesn't seem to be much activity on this project. However this layer is listed on the OpenEmbedded layer here

https://layers.openembedded.org/layerindex/branch/master/layer/meta-pine64/

We have received a request to add this layer in the index:
https://github.com/alistair23/meta-pine64/

I would like to know if it's ok to remove the old layer and replace with this new one since it looks like someone wants to maintain it.

thanks

**Comment by mont3z** [comment]
Hi Nicholas,

Thanks for your email. I’m actually currently working on different projects. So please feel free to replace to the new updated layer.

Thx
Montez

**Comment by ndechesne** [comment]
Many thanks for the quick response! we've done the update on the OE layer index.
